application:
  id: "adam-simple-stream"
security:
  protocol: SASL_SSL
sasl:
  mechanism: PLAIN
  jaas:
    config: org.apache.kafka.common.security.plain.PlainLoginModule   required username='xxx'   password='yyy';
bootstrap:
  servers: "your-bootstrap-server:9092"
schema:
  registry:
    url: "https://any-sr.aws.confluent.cloud"
basic:
  auth:
    user:
      info: user:pass
    credentials:
      source: USER_INFO
dlq:
  topic: "DLQ_TOPIC"
